// Generated by gencpp from file data_capture/ImageSaveRequest.msg
// DO NOT EDIT!


#ifndef DATA_CAPTURE_MESSAGE_IMAGESAVEREQUEST_H
#define DATA_CAPTURE_MESSAGE_IMAGESAVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace data_capture
{
template <class ContainerAllocator>
struct ImageSaveRequest_
{
  typedef ImageSaveRequest_<ContainerAllocator> Type;

  ImageSaveRequest_()
    : image_path()  {
    }
  ImageSaveRequest_(const ContainerAllocator& _alloc)
    : image_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _image_path_type;
  _image_path_type image_path;





  typedef boost::shared_ptr< ::data_capture::ImageSaveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::data_capture::ImageSaveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ImageSaveRequest_

typedef ::data_capture::ImageSaveRequest_<std::allocator<void> > ImageSaveRequest;

typedef boost::shared_ptr< ::data_capture::ImageSaveRequest > ImageSaveRequestPtr;
typedef boost::shared_ptr< ::data_capture::ImageSaveRequest const> ImageSaveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::data_capture::ImageSaveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::data_capture::ImageSaveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace data_capture

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::data_capture::ImageSaveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_capture::ImageSaveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_capture::ImageSaveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_capture::ImageSaveRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_capture::ImageSaveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_capture::ImageSaveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::data_capture::ImageSaveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65568c775bfbc96c6265c3d13d7e1a07";
  }

  static const char* value(const ::data_capture::ImageSaveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65568c775bfbc96cULL;
  static const uint64_t static_value2 = 0x6265c3d13d7e1a07ULL;
};

template<class ContainerAllocator>
struct DataType< ::data_capture::ImageSaveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "data_capture/ImageSaveRequest";
  }

  static const char* value(const ::data_capture::ImageSaveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::data_capture::ImageSaveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string image_path\n\
";
  }

  static const char* value(const ::data_capture::ImageSaveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::data_capture::ImageSaveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageSaveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::data_capture::ImageSaveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::data_capture::ImageSaveRequest_<ContainerAllocator>& v)
  {
    s << indent << "image_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.image_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATA_CAPTURE_MESSAGE_IMAGESAVEREQUEST_H
